# Generated by Django 6.0 on 2025-12-05 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Heure début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure fin')),
                ('lieu', models.CharField(max_length=255, verbose_name='Lieu')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse complète')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('categorie', models.CharField(choices=[('conseil', 'Conseil municipal'), ('reunion', 'Réunion publique'), ('culturel', 'Événement culturel'), ('sportif', 'Événement sportif'), ('festif', 'Fête / Cérémonie'), ('marche', 'Marché'), ('associatif', 'Événement associatif'), ('formation', 'Formation / Atelier'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Catégorie')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('reporte', 'Reporté'), ('termine', 'Terminé')], default='planifie', max_length=20, verbose_name='Statut')),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/', verbose_name='Image')),
                ('contact_organisateur', models.CharField(blank=True, max_length=255, verbose_name='Contact organisateur')),
                ('inscription_requise', models.BooleanField(default=False, verbose_name='Inscription requise')),
                ('places_limitees', models.BooleanField(default=False, verbose_name='Places limitées')),
                ('nombre_places', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de places')),
                ('est_public', models.BooleanField(default=True, verbose_name='Public')),
                ('est_mis_en_avant', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('est_recurrent', models.BooleanField(default=False, verbose_name='Récurrent')),
                ('recurrence', models.CharField(blank=True, max_length=50, verbose_name='Récurrence')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='communes.commune')),
                ('organisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_organises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date', 'heure_debut'],
                'unique_together': {('commune', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='InscriptionEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('nombre_personnes', models.PositiveIntegerField(default=1, verbose_name='Nombre de personnes')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('present', 'Présent'), ('absent', 'Absent')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name='Date inscription')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='evenements.evenement')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_evenements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription événement',
                'verbose_name_plural': 'Inscriptions événements',
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_demandeur', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('email_demandeur', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone_demandeur', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Heure début')),
                ('heure_fin', models.TimeField(verbose_name='Heure fin')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé'), ('absent', 'Absent')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='communes.commune')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='communes.servicemunicipal')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['date', 'heure_debut'],
            },
        ),
    ]
