# Generated by Django 6.0 on 2025-12-05 02:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Numero')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('resume', models.TextField(blank=True, verbose_name='Resume')),
                ('date_seance', models.DateField(verbose_name='Date de seance')),
                ('fichier', models.FileField(upload_to='deliberations/', verbose_name='Fichier PDF')),
                ('est_publie', models.BooleanField(default=True, verbose_name='Publie')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date creation')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', to='communes.commune')),
            ],
            options={
                'verbose_name': 'Deliberation',
                'verbose_name_plural': 'Deliberations',
                'ordering': ['-date_seance'],
            },
        ),
        migrations.CreateModel(
            name='DocumentBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('budget_primitif', 'Budget primitif'), ('budget_supplementaire', 'Budget supplementaire'), ('compte_administratif', 'Compte administratif'), ('rapport_activite', 'Rapport activite'), ('autre', 'Autre')], max_length=50, verbose_name='Type')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('annee', models.PositiveIntegerField(verbose_name='Annee')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fichier', models.FileField(upload_to='budgets/', verbose_name='Fichier')),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant total (FCFA)')),
                ('est_publie', models.BooleanField(default=True, verbose_name='Publie')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date creation')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_budgetaires', to='communes.commune')),
            ],
            options={
                'verbose_name': 'Document budgetaire',
                'verbose_name_plural': 'Documents budgetaires',
                'ordering': ['-annee', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DocumentOfficiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('type_document', models.CharField(choices=[('arrete', 'Arrete'), ('reglement', 'Reglement'), ('compte_rendu', 'Compte-rendu'), ('formulaire', 'Formulaire'), ('guide', 'Guide'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fichier', models.FileField(upload_to='documents/', verbose_name='Fichier')),
                ('categorie', models.CharField(blank=True, max_length=100, verbose_name='Categorie')),
                ('numero_reference', models.CharField(blank=True, max_length=100, verbose_name='Numero de reference')),
                ('date_document', models.DateField(blank=True, null=True, verbose_name='Date du document')),
                ('est_public', models.BooleanField(default=True, verbose_name='Public')),
                ('nombre_telechargements', models.PositiveIntegerField(default=0, verbose_name='Telechargements')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date creation')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_publies', to=settings.AUTH_USER_MODEL)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_officiels', to='communes.commune')),
            ],
            options={
                'verbose_name': 'Document officiel',
                'verbose_name_plural': 'Documents officiels',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Budget alloue (FCFA)')),
                ('budget_depense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Budget depense')),
                ('avancement', models.PositiveIntegerField(default=0, verbose_name='Avancement (%)')),
                ('date_debut', models.DateField(verbose_name='Date debut')),
                ('date_fin', models.DateField(verbose_name='Date fin prevue')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='Date fin reelle')),
                ('categorie', models.CharField(choices=[('voirie', 'Voirie et infrastructures'), ('batiments', 'Batiments publics'), ('espaces_verts', 'Espaces verts'), ('culture', 'Culture et patrimoine'), ('sport', 'Sport et loisirs'), ('education', 'Education'), ('social', 'Action sociale'), ('environnement', 'Environnement'), ('numerique', 'Numerique'), ('sante', 'Sante'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Categorie')),
                ('statut', models.CharField(choices=[('planifie', 'Planifie'), ('en_cours', 'En cours'), ('suspendu', 'Suspendu'), ('termine', 'Termine'), ('annule', 'Annule')], default='planifie', max_length=20, verbose_name='Statut')),
                ('lieu', models.CharField(blank=True, max_length=255, verbose_name='Lieu')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='projets/', verbose_name='Image principale')),
                ('est_public', models.BooleanField(default=True, verbose_name='Public')),
                ('est_mis_en_avant', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date creation')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Derniere modification')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='communes.commune')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_creation'],
                'unique_together': {('commune', 'slug')},
            },
        ),
    ]
