# Generated by Django 6.0 on 2025-12-04 20:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("mairies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="Nom complet")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin_national", "Administrateur National"),
                            ("agent_communal", "Agent Communal"),
                            ("citoyen", "Citoyen"),
                        ],
                        default="citoyen",
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                ("adresse", models.TextField(blank=True, verbose_name="Adresse")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Staff")),
                (
                    "date_inscription",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'inscription",
                    ),
                ),
                (
                    "derniere_connexion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière connexion"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "mairie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="utilisateurs",
                        to="mairies.mairie",
                        verbose_name="Mairie rattachée",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["-date_inscription"],
            },
        ),
        migrations.CreateModel(
            name="ProfilAgentCommunal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "poste",
                    models.CharField(blank=True, max_length=255, verbose_name="Poste"),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Service"
                    ),
                ),
                (
                    "matricule",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Matricule"
                    ),
                ),
                (
                    "peut_gerer_contenu",
                    models.BooleanField(
                        default=True, verbose_name="Peut gérer le contenu"
                    ),
                ),
                (
                    "peut_gerer_formulaires",
                    models.BooleanField(
                        default=True, verbose_name="Peut gérer les formulaires"
                    ),
                ),
                (
                    "peut_gerer_projets",
                    models.BooleanField(
                        default=True, verbose_name="Peut gérer les projets"
                    ),
                ),
                (
                    "peut_gerer_evenements",
                    models.BooleanField(
                        default=True, verbose_name="Peut gérer les événements"
                    ),
                ),
                (
                    "peut_gerer_documents",
                    models.BooleanField(
                        default=True, verbose_name="Peut gérer les documents"
                    ),
                ),
                (
                    "date_prise_fonction",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de prise de fonction"
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        limit_choices_to={"role": "agent_communal"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil_agent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Agent Communal",
                "verbose_name_plural": "Profils Agents Communaux",
            },
        ),
        migrations.CreateModel(
            name="ProfilCitoyen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_naissance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "lieu_naissance",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Lieu de naissance"
                    ),
                ),
                (
                    "numero_identite",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro d'identité"
                    ),
                ),
                (
                    "notification_email",
                    models.BooleanField(
                        default=True, verbose_name="Notifications par email"
                    ),
                ),
                (
                    "notification_sms",
                    models.BooleanField(
                        default=False, verbose_name="Notifications par SMS"
                    ),
                ),
                (
                    "abonne_newsletter",
                    models.BooleanField(
                        default=False, verbose_name="Abonné à la newsletter"
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        limit_choices_to={"role": "citoyen"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil_citoyen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Citoyen",
                "verbose_name_plural": "Profils Citoyens",
            },
        ),
    ]
