# Generated by Django 6.0 on 2025-12-04 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="email_verifie",
            field=models.BooleanField(default=False, verbose_name="Email vérifié"),
        ),
        migrations.CreateModel(
            name="TokenVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=64, unique=True, verbose_name="Token"),
                ),
                (
                    "type_token",
                    models.CharField(
                        choices=[
                            ("email_verification", "Vérification Email"),
                            ("password_reset", "Réinitialisation Mot de Passe"),
                        ],
                        max_length=20,
                        verbose_name="Type de token",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_expiration",
                    models.DateTimeField(verbose_name="Date d'expiration"),
                ),
                (
                    "est_utilise",
                    models.BooleanField(default=False, verbose_name="Utilisé"),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens_verification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de vérification",
                "verbose_name_plural": "Tokens de vérification",
                "ordering": ["-date_creation"],
            },
        ),
    ]
