# Generated by Django 6.0 on 2025-12-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_utilisateur_email_verifie_tokenverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin_national", "Administrateur National"),
                    ("agent_communal", "Agent Communal"),
                ],
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
        migrations.DeleteModel(
            name="ProfilCitoyen",
        ),
    ]
