# Generated by Django 6.0 on 2025-12-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_citoyen_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenverification",
            name="code_otp",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Code OTP"
            ),
        ),
        migrations.AddField(
            model_name="tokenverification",
            name="otp_verifie",
            field=models.BooleanField(default=False, verbose_name="OTP vérifié"),
        ),
        migrations.AlterField(
            model_name="tokenverification",
            name="token",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="Token/Code OTP"
            ),
        ),
        migrations.AlterField(
            model_name="tokenverification",
            name="type_token",
            field=models.CharField(
                choices=[
                    ("email_verification", "Vérification Email"),
                    ("password_reset_otp", "Code OTP Réinitialisation"),
                ],
                max_length=20,
                verbose_name="Type de token",
            ),
        ),
    ]
