# Generated by Django 4.2.27 on 2025-12-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_otp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL Avatar'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Email vérifié (API)'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom de famille'),
        ),
        migrations.AlterField(
            model_name='tokenverification',
            name='type_token',
            field=models.CharField(choices=[('email_verification', 'Vérification Email'), ('email_verification_otp', 'Code OTP Email'), ('password_reset_otp', 'Code OTP Réinitialisation')], max_length=30, verbose_name='Type de token'),
        ),
    ]
