# Generated by Django 6.0 on 2025-12-05 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_new_message",
                    models.BooleanField(
                        default=True, verbose_name="Email nouveau message"
                    ),
                ),
                (
                    "email_new_comment",
                    models.BooleanField(
                        default=True, verbose_name="Email nouveau commentaire"
                    ),
                ),
                (
                    "email_event_reminder",
                    models.BooleanField(
                        default=True, verbose_name="Email rappel événement"
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Push notifications"
                    ),
                ),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("realtime", "Temps réel"),
                            ("daily", "Quotidien"),
                            ("weekly", "Hebdomadaire"),
                            ("never", "Jamais"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="Fréquence digest",
                    ),
                ),
                (
                    "two_factor_enabled",
                    models.BooleanField(default=False, verbose_name="2FA activé"),
                ),
                (
                    "two_factor_secret",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Secret 2FA"
                    ),
                ),
                (
                    "session_timeout",
                    models.PositiveIntegerField(
                        default=3600, verbose_name="Timeout session (sec)"
                    ),
                ),
                (
                    "language",
                    models.CharField(default="fr", max_length=5, verbose_name="Langue"),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Africa/Douala",
                        max_length=50,
                        verbose_name="Fuseau horaire",
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="DD/MM/YYYY", max_length=20, verbose_name="Format date"
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        default="24h", max_length=5, verbose_name="Format heure"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres utilisateur",
                "verbose_name_plural": "Paramètres utilisateurs",
            },
        ),
    ]
