# Generated by Django 6.0 on 2025-12-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemarcheAdministrative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(max_length=100, verbose_name="Type de démarche"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours de traitement"),
                            ("validee", "Validée"),
                            ("rejetee", "Rejetée"),
                            ("completee", "Complétée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_demande",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de demande"
                    ),
                ),
                (
                    "donnees_formulaire",
                    models.JSONField(default=dict, verbose_name="Données soumises"),
                ),
                (
                    "nom_demandeur",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nom du demandeur"
                    ),
                ),
                (
                    "email_demandeur",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email du demandeur"
                    ),
                ),
                (
                    "telephone_demandeur",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone du demandeur"
                    ),
                ),
                (
                    "numero_suivi",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro de suivi",
                    ),
                ),
                (
                    "commentaire_agent",
                    models.TextField(blank=True, verbose_name="Commentaire de l'agent"),
                ),
                (
                    "motif_rejet",
                    models.TextField(blank=True, verbose_name="Motif de rejet"),
                ),
                (
                    "date_prise_en_charge",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de prise en charge"
                    ),
                ),
                (
                    "date_traitement",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de traitement"
                    ),
                ),
                (
                    "priorite",
                    models.PositiveIntegerField(default=0, verbose_name="Priorité"),
                ),
            ],
            options={
                "verbose_name": "Démarche Administrative",
                "verbose_name_plural": "Démarches Administratives",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.CreateModel(
            name="Formulaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("acte_naissance", "Demande d'acte de naissance"),
                            ("acte_mariage", "Demande d'acte de mariage"),
                            ("acte_deces", "Demande d'acte de décès"),
                            ("signalement", "Signalement de problème"),
                            ("contact", "Formulaire de contact"),
                            ("demande_info", "Demande d'information"),
                            ("inscription", "Inscription à un service"),
                            ("reclamation", "Réclamation"),
                            ("autre", "Autre"),
                        ],
                        default="contact",
                        max_length=50,
                        verbose_name="Type de formulaire",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=255, verbose_name="Nom du formulaire"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "champs_dynamiques",
                    models.JSONField(
                        default=list,
                        help_text="Configuration JSON des champs du formulaire",
                        verbose_name="Champs du formulaire",
                    ),
                ),
                (
                    "necessite_authentification",
                    models.BooleanField(
                        default=False,
                        help_text="Si activé, seuls les utilisateurs connectés peuvent soumettre",
                        verbose_name="Nécessite une authentification",
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(default=True, verbose_name="Formulaire actif"),
                ),
                (
                    "email_notification",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de notification"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Formulaire",
                "verbose_name_plural": "Formulaires",
                "ordering": ["mairie", "type", "nom"],
            },
        ),
        migrations.CreateModel(
            name="RendezVous",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        max_length=255, verbose_name="Motif du rendez-vous"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("heure_debut", models.TimeField(verbose_name="Heure de début")),
                ("heure_fin", models.TimeField(verbose_name="Heure de fin")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de confirmation"),
                            ("confirme", "Confirmé"),
                            ("annule", "Annulé"),
                            ("termine", "Terminé"),
                            ("absent", "Absent"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendez-vous",
                "verbose_name_plural": "Rendez-vous",
                "ordering": ["date", "heure_debut"],
            },
        ),
        migrations.CreateModel(
            name="Signalement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("voirie", "Voirie (nids-de-poule, trottoirs...)"),
                            ("eclairage", "Éclairage public"),
                            ("proprete", "Propreté (dépôts sauvages...)"),
                            ("espaces_verts", "Espaces verts"),
                            ("stationnement", "Stationnement"),
                            ("bruit", "Nuisances sonores"),
                            ("securite", "Sécurité"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=50,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="signalements/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "email_contact",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de contact"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("signale", "Signalé"),
                            ("en_cours", "En cours de traitement"),
                            ("resolu", "Résolu"),
                            ("rejete", "Rejeté"),
                        ],
                        default="signale",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "commentaire_resolution",
                    models.TextField(
                        blank=True, verbose_name="Commentaire de résolution"
                    ),
                ),
                (
                    "date_signalement",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de signalement"
                    ),
                ),
                (
                    "date_resolution",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de résolution"
                    ),
                ),
                (
                    "numero_suivi",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro de suivi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signalement",
                "verbose_name_plural": "Signalements",
                "ordering": ["-date_signalement"],
            },
        ),
    ]
