# Generated by Django 6.0 on 2025-12-04 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("demarches", "0001_initial"),
        ("mairies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="demarcheadministrative",
            name="agent_traitant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demarches_traitees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="demarcheadministrative",
            name="demandeur",
            field=models.ForeignKey(
                blank=True,
                help_text="Peut être null pour les signalements anonymes",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demarches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="demarcheadministrative",
            name="mairie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demarches",
                to="mairies.mairie",
            ),
        ),
        migrations.AddField(
            model_name="formulaire",
            name="mairie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formulaires",
                to="mairies.mairie",
            ),
        ),
        migrations.AddField(
            model_name="demarcheadministrative",
            name="formulaire",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demarches",
                to="demarches.formulaire",
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="citoyen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rendez_vous",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="mairie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rendez_vous",
                to="mairies.mairie",
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rendez_vous",
                to="mairies.servicemunicipal",
            ),
        ),
        migrations.AddField(
            model_name="signalement",
            name="agent_traitant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signalements_traites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="signalement",
            name="mairie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signalements",
                to="mairies.mairie",
            ),
        ),
        migrations.AddField(
            model_name="signalement",
            name="signaleur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signalements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
