# Generated by Django 6.0 on 2025-12-05 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mairies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publié"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publié le"
                    ),
                ),
                (
                    "theme",
                    models.JSONField(blank=True, default=dict, verbose_name="Thème"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="Meta titre"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta description"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="website/favicons/",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "social_links",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Réseaux sociaux"
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Google Analytics ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mairie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_config",
                        to="mairies.mairie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration du site",
                "verbose_name_plural": "Configurations des sites",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_id",
                    models.CharField(max_length=50, verbose_name="ID section"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero/Bannière"),
                            ("services", "Services"),
                            ("events", "Événements"),
                            ("news", "Actualités"),
                            ("contact", "Contact"),
                            ("gallery", "Galerie"),
                            ("team", "Équipe"),
                            ("custom", "Personnalisée"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Visible"),
                ),
                ("content", models.JSONField(default=dict, verbose_name="Contenu")),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="website.websiteconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("website", "section_id")},
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                ("slug", models.SlugField(max_length=255, verbose_name="Slug")),
                ("content", models.TextField(verbose_name="Contenu HTML")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publié"),
                ),
                (
                    "in_menu",
                    models.BooleanField(default=False, verbose_name="Dans le menu"),
                ),
                (
                    "menu_order",
                    models.PositiveIntegerField(default=0, verbose_name="Ordre menu"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="Meta titre"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="website.websiteconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["menu_order"],
                "unique_together": {("website", "slug")},
            },
        ),
    ]
