# Generated by Django 6.0 on 2025-12-05 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('est_lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('est_traite', models.BooleanField(default=False, verbose_name='Traité')),
                ('reponse', models.TextField(blank=True, verbose_name='Réponse')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name='Date envoi')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date réponse')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='communes.commune')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('etat_civil', 'État Civil'), ('urbanisme', 'Urbanisme'), ('social', 'Action Sociale'), ('scolaire', 'Scolaire'), ('signalement', 'Signalement'), ('contact', 'Contact'), ('demande_info', 'Demande d information'), ('reclamation', 'Réclamation'), ('autre', 'Autre')], default='contact', max_length=50, verbose_name='Type')),
                ('champs', models.JSONField(default=list, help_text='Configuration JSON des champs', verbose_name='Champs du formulaire')),
                ('necessite_authentification', models.BooleanField(default=False, verbose_name='Authentification requise')),
                ('email_notification', models.EmailField(blank=True, max_length=254, verbose_name='Email notification')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulaires', to='communes.commune')),
            ],
            options={
                'verbose_name': 'Formulaire',
                'verbose_name_plural': 'Formulaires',
                'ordering': ['type', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Demarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_suivi', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro de suivi')),
                ('type', models.CharField(max_length=100, verbose_name='Type de démarche')),
                ('donnees', models.JSONField(default=dict, verbose_name='Données soumises')),
                ('nom_demandeur', models.CharField(blank=True, max_length=255, verbose_name='Nom demandeur')),
                ('email_demandeur', models.EmailField(blank=True, max_length=254, verbose_name='Email demandeur')),
                ('telephone_demandeur', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('validee', 'Validée'), ('rejetee', 'Rejetée'), ('completee', 'Complétée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('commentaire_agent', models.TextField(blank=True, verbose_name='Commentaire agent')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif rejet')),
                ('priorite', models.PositiveIntegerField(default=0, verbose_name='Priorité')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date demande')),
                ('date_prise_en_charge', models.DateTimeField(blank=True, null=True, verbose_name='Date prise en charge')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date traitement')),
                ('agent_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demarches_traitees', to=settings.AUTH_USER_MODEL)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demarches', to='communes.commune')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demarches', to=settings.AUTH_USER_MODEL)),
                ('formulaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demarches', to='services.formulaire')),
            ],
            options={
                'verbose_name': 'Démarche',
                'verbose_name_plural': 'Démarches',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_suivi', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro de suivi')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('categorie', models.CharField(choices=[('voirie', 'Voirie'), ('eclairage', 'Éclairage public'), ('proprete', 'Propreté'), ('espaces_verts', 'Espaces verts'), ('stationnement', 'Stationnement'), ('bruit', 'Nuisances sonores'), ('securite', 'Sécurité'), ('eau', 'Eau / Assainissement'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Catégorie')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='signalements/', verbose_name='Photo')),
                ('email_contact', models.EmailField(blank=True, max_length=254, verbose_name='Email contact')),
                ('statut', models.CharField(choices=[('signale', 'Signalé'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('rejete', 'Rejeté')], default='signale', max_length=20, verbose_name='Statut')),
                ('commentaire_resolution', models.TextField(blank=True, verbose_name='Commentaire résolution')),
                ('date_signalement', models.DateTimeField(auto_now_add=True, verbose_name='Date signalement')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date résolution')),
                ('agent_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_traites', to=settings.AUTH_USER_MODEL)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='communes.commune')),
                ('signaleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-date_signalement'],
            },
        ),
    ]
