# Generated by Django 6.0 on 2025-12-05 02:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('communes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationPortail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_portail', models.CharField(default='E-CMS Cameroun', max_length=255, verbose_name='Nom du portail')),
                ('slogan', models.CharField(blank=True, max_length=500, verbose_name='Slogan')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='portail/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='portail/', verbose_name='Favicon')),
                ('banniere', models.ImageField(blank=True, null=True, upload_to='portail/', verbose_name='Bannière')),
                ('couleur_primaire', models.CharField(default='#0066CC', max_length=7, verbose_name='Couleur primaire')),
                ('couleur_secondaire', models.CharField(default='#004499', max_length=7, verbose_name='Couleur secondaire')),
                ('email_contact', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('meta_titre', models.CharField(blank=True, max_length=70, verbose_name='Meta titre')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Configuration du portail',
                'verbose_name_plural': 'Configuration du portail',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='utilisateurs/', verbose_name='Photo de profil')),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrateur'), ('admin_commune', 'Administrateur Commune'), ('editeur', 'Éditeur'), ('moderateur', 'Modérateur')], default='editeur', max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('email_verifie', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date d inscription')),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='communes.commune', verbose_name='Commune rattachée')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='TokenVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('type_token', models.CharField(choices=[('email_verification', 'Vérification Email'), ('password_reset', 'Réinitialisation Mot de Passe')], max_length=20, verbose_name='Type')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_expiration', models.DateTimeField(verbose_name='Date expiration')),
                ('est_utilise', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de vérification',
                'verbose_name_plural': 'Tokens de vérification',
            },
        ),
    ]
