# Generated by Django 6.0 on 2025-12-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbonneNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('nom', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name='Date inscription')),
                ('token_desinscription', models.CharField(blank=True, max_length=64, verbose_name='Token désinscription')),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
            },
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('resume', models.TextField(blank=True, max_length=500, verbose_name='Résumé')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='actualites/', verbose_name='Image principale')),
                ('categorie', models.CharField(choices=[('communique', 'Communiqué de presse'), ('avis_public', 'Avis public'), ('nouvelle', 'Nouvelle'), ('annonce', 'Annonce'), ('vie_municipale', 'Vie municipale'), ('culture', 'Culture'), ('education', 'Éducation'), ('sport', 'Sport')], default='nouvelle', max_length=50, verbose_name='Catégorie')),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=255, verbose_name='Tags')),
                ('est_publie', models.BooleanField(default=False, verbose_name='Publié')),
                ('est_mis_en_avant', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('nombre_vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('reponse', models.TextField(verbose_name='Réponse')),
                ('categorie', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['categorie', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('planifiee', 'Planifiée'), ('envoyee', 'Envoyée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name='Date envoi')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('nombre_destinataires', models.PositiveIntegerField(default=0, verbose_name='Destinataires')),
                ('nombre_ouvertures', models.PositiveIntegerField(default=0, verbose_name='Ouvertures')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PageCMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug URL')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('afficher_dans_menu', models.BooleanField(default=True, verbose_name='Afficher dans le menu')),
                ('est_publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('meta_titre', models.CharField(blank=True, max_length=70, verbose_name='Meta titre')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('image_bandeau', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Image bandeau')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Page CMS',
                'verbose_name_plural': 'Pages CMS',
                'ordering': ['ordre', 'titre'],
            },
        ),
    ]
