# Generated by Django 6.0 on 2025-12-05 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actualites', '0001_initial'),
        ('communes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnenewsletter',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnes_newsletter', to='communes.commune'),
        ),
    ]
