# Generated by Django 6.0 on 2025-12-05 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actualites', '0002_initial'),
        ('communes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actualite',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualites', to='communes.commune'),
        ),
        migrations.AddField(
            model_name='faq',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='communes.commune'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='communes.commune'),
        ),
        migrations.AddField(
            model_name='pagecms',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='communes.commune'),
        ),
        migrations.AddField(
            model_name='pagecms',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='actualites.pagecms'),
        ),
        migrations.AlterUniqueTogether(
            name='abonnenewsletter',
            unique_together={('commune', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='actualite',
            unique_together={('commune', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='pagecms',
            unique_together={('commune', 'slug')},
        ),
    ]
