# Generated by Django 6.0 on 2025-12-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actualite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                ("slug", models.SlugField(max_length=255, verbose_name="Slug")),
                (
                    "resume",
                    models.TextField(blank=True, max_length=500, verbose_name="Résumé"),
                ),
                ("contenu", models.TextField(verbose_name="Contenu")),
                (
                    "image_principale",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="actualites/",
                        verbose_name="Image principale",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("communique", "Communiqué de presse"),
                            ("avis_public", "Avis public"),
                            ("nouvelle", "Nouvelle"),
                            ("annonce", "Annonce"),
                            ("evenement", "Événement"),
                        ],
                        default="nouvelle",
                        max_length=50,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "est_publie",
                    models.BooleanField(default=False, verbose_name="Publié"),
                ),
                (
                    "est_mis_en_avant",
                    models.BooleanField(default=False, verbose_name="Mis en avant"),
                ),
                (
                    "date_publication",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "nombre_vues",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de vues"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Actualité",
                "verbose_name_plural": "Actualités",
                "ordering": ["-date_publication"],
            },
        ),
        migrations.CreateModel(
            name="DocumentOfficiel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "fichier_joint",
                    models.FileField(upload_to="documents/", verbose_name="Fichier"),
                ),
                (
                    "date_publication",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("deliberation", "Délibération du conseil municipal"),
                            ("arrete", "Arrêté municipal"),
                            ("compte_rendu", "Compte-rendu de réunion"),
                            ("budget", "Budget"),
                            ("reglement", "Règlement"),
                            ("formulaire", "Formulaire téléchargeable"),
                            ("rapport", "Rapport"),
                            ("autre", "Autre document"),
                        ],
                        default="autre",
                        max_length=50,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "categorie",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Catégorie"
                    ),
                ),
                (
                    "annee",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Année"
                    ),
                ),
                (
                    "numero_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Numéro de référence"
                    ),
                ),
                (
                    "est_public",
                    models.BooleanField(default=True, verbose_name="Document public"),
                ),
                (
                    "est_mis_en_avant",
                    models.BooleanField(default=False, verbose_name="Mis en avant"),
                ),
                (
                    "taille_fichier",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Taille du fichier (octets)"
                    ),
                ),
                (
                    "type_mime",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Type MIME"
                    ),
                ),
                (
                    "nombre_telechargements",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de téléchargements"
                    ),
                ),
                (
                    "date_document",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date du document"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Officiel",
                "verbose_name_plural": "Documents Officiels",
                "ordering": ["-date_publication"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Question")),
                ("reponse", models.TextField(verbose_name="Réponse")),
                (
                    "categorie",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Catégorie"
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "est_active",
                    models.BooleanField(default=True, verbose_name="Active"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["categorie", "ordre"],
            },
        ),
        migrations.CreateModel(
            name="PageCMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                ("slug", models.SlugField(max_length=255, verbose_name="Slug URL")),
                ("contenu", models.TextField(verbose_name="Contenu")),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "afficher_dans_menu",
                    models.BooleanField(
                        default=True, verbose_name="Afficher dans le menu"
                    ),
                ),
                (
                    "est_publie",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                (
                    "meta_titre",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="Meta titre"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta description"
                    ),
                ),
                (
                    "image_bandeau",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pages/",
                        verbose_name="Image bandeau",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Page CMS",
                "verbose_name_plural": "Pages CMS",
                "ordering": ["ordre", "titre"],
            },
        ),
    ]
