# Generated by Django 6.0 on 2025-12-04 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("mairies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="actualite",
            name="auteur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actualites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="actualite",
            name="mairie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actualites",
                to="mairies.mairie",
            ),
        ),
        migrations.AddField(
            model_name="documentofficiel",
            name="auteur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_publies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentofficiel",
            name="mairie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="mairies.mairie",
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="mairie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faqs",
                to="mairies.mairie",
            ),
        ),
        migrations.AddField(
            model_name="pagecms",
            name="mairie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="mairies.mairie",
            ),
        ),
        migrations.AddField(
            model_name="pagecms",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enfants",
                to="documents.pagecms",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="actualite",
            unique_together={("mairie", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="pagecms",
            unique_together={("mairie", "slug")},
        ),
    ]
