# Generated by Django 6.0 on 2025-12-04 20:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentProjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "fichier",
                    models.FileField(
                        upload_to="projets/documents/", verbose_name="Fichier"
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("plan", "Plan"),
                            ("etude", "Étude"),
                            ("marche", "Marché public"),
                            ("rapport", "Rapport"),
                            ("photo", "Photographie"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "est_public",
                    models.BooleanField(default=True, verbose_name="Public"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
            ],
            options={
                "verbose_name": "Document de projet",
                "verbose_name_plural": "Documents de projets",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="MiseAJourProjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        max_length=255, verbose_name="Titre de la mise à jour"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "avancement",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Avancement (%)"
                    ),
                ),
                (
                    "budget_depense",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Budget dépensé (€)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projets/mises_a_jour/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mise à jour de projet",
                "verbose_name_plural": "Mises à jour de projets",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=255, verbose_name="Titre du projet"),
                ),
                ("slug", models.SlugField(max_length=255, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Budget alloué (€)",
                    ),
                ),
                (
                    "avancement",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Pourcentage de réalisation (0-100)",
                        verbose_name="Avancement (%)",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin prévue")),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("voirie", "Voirie et infrastructures"),
                            ("batiments", "Bâtiments publics"),
                            ("espaces_verts", "Espaces verts"),
                            ("culture", "Culture et patrimoine"),
                            ("sport", "Sport et loisirs"),
                            ("education", "Éducation"),
                            ("social", "Action sociale"),
                            ("environnement", "Environnement"),
                            ("numerique", "Numérique"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=50,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("suspendu", "Suspendu"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="planifie",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "budget_depense",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Budget dépensé (€)",
                    ),
                ),
                (
                    "image_principale",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projets/",
                        verbose_name="Image principale",
                    ),
                ),
                (
                    "lieu",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Lieu / Adresse"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "est_public",
                    models.BooleanField(
                        default=True, verbose_name="Visible publiquement"
                    ),
                ),
                (
                    "est_mis_en_avant",
                    models.BooleanField(default=False, verbose_name="Mis en avant"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "date_fin_reelle",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fin réelle"
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["-date_creation"],
            },
        ),
    ]
