# Generated by Django 6.0 on 2025-12-04 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mairies", "0001_initial"),
        ("projets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="miseajourprojet",
            name="auteur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="mairie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projets",
                to="mairies.mairie",
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projets_responsable",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="miseajourprojet",
            name="projet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mises_a_jour",
                to="projets.projet",
            ),
        ),
        migrations.AddField(
            model_name="documentprojet",
            name="projet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="projets.projet",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projet",
            unique_together={("mairie", "slug")},
        ),
    ]
