# Generated by Django 6.0 on 2025-12-04 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mairies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InscriptionEvenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("confirme", "Confirmé"),
                            ("annule", "Annulé"),
                            ("present", "Présent"),
                            ("absent", "Absent"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "nombre_personnes",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre de personnes"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "date_inscription",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'inscription"
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription à un événement",
                "verbose_name_plural": "Inscriptions aux événements",
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                ("contenu", models.TextField(verbose_name="Contenu")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("planifiee", "Planifiée"),
                            ("envoyee", "Envoyée"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_envoi",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "nombre_destinataires",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de destinataires"
                    ),
                ),
                (
                    "nombre_ouvertures",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'ouvertures"
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter",
                "verbose_name_plural": "Newsletters",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="AbonneNewsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "nom",
                    models.CharField(blank=True, max_length=255, verbose_name="Nom"),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_inscription",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'inscription"
                    ),
                ),
                (
                    "date_desinscription",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de désinscription"
                    ),
                ),
                (
                    "token_desinscription",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Token de désinscription",
                    ),
                ),
                (
                    "mairie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonnes_newsletter",
                        to="mairies.mairie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonné newsletter",
                "verbose_name_plural": "Abonnés newsletter",
            },
        ),
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=255, verbose_name="Nom de l'événement"),
                ),
                ("slug", models.SlugField(max_length=255, verbose_name="Slug")),
                ("description", models.TextField(verbose_name="Description")),
                ("lieu", models.CharField(max_length=255, verbose_name="Lieu")),
                ("date", models.DateField(verbose_name="Date")),
                ("heure_debut", models.TimeField(verbose_name="Heure de début")),
                (
                    "heure_fin",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de fin"
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("conseil", "Conseil municipal"),
                            ("reunion", "Réunion publique"),
                            ("culturel", "Événement culturel"),
                            ("sportif", "Événement sportif"),
                            ("festif", "Fête / Cérémonie"),
                            ("marche", "Marché"),
                            ("associatif", "Événement associatif"),
                            ("formation", "Formation / Atelier"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=50,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("confirme", "Confirmé"),
                            ("annule", "Annulé"),
                            ("reporte", "Reporté"),
                            ("termine", "Terminé"),
                        ],
                        default="planifie",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="evenements/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "contact_organisateur",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Contact organisateur"
                    ),
                ),
                (
                    "inscription_requise",
                    models.BooleanField(
                        default=False, verbose_name="Inscription requise"
                    ),
                ),
                (
                    "places_limitees",
                    models.BooleanField(default=False, verbose_name="Places limitées"),
                ),
                (
                    "nombre_places",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Nombre de places"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "est_public",
                    models.BooleanField(default=True, verbose_name="Événement public"),
                ),
                (
                    "est_mis_en_avant",
                    models.BooleanField(default=False, verbose_name="Mis en avant"),
                ),
                (
                    "est_recurrent",
                    models.BooleanField(
                        default=False, verbose_name="Événement récurrent"
                    ),
                ),
                (
                    "recurrence",
                    models.CharField(
                        blank=True,
                        help_text="Ex: hebdomadaire, mensuel, annuel",
                        max_length=50,
                        verbose_name="Récurrence",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "mairie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenements",
                        to="mairies.mairie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["date", "heure_debut"],
            },
        ),
    ]
