# Generated by Django 6.0 on 2025-12-04 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("evenements", "0001_initial"),
        ("mairies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="organisateur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evenements_organises",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inscriptionevenement",
            name="evenement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscriptions",
                to="evenements.evenement",
            ),
        ),
        migrations.AddField(
            model_name="inscriptionevenement",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscriptions_evenements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="auteur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="mairie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletters",
                to="mairies.mairie",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="abonnenewsletter",
            unique_together={("mairie", "email")},
        ),
        migrations.AlterUniqueTogether(
            name="evenement",
            unique_together={("mairie", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="inscriptionevenement",
            unique_together={("evenement", "participant")},
        ),
    ]
