# Generated by Django 6.0 on 2025-12-05 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['region', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la commune')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug URL')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='Population')),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie (km²)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse complète')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web officiel')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='communes/logos/', verbose_name='Logo')),
                ('banniere', models.ImageField(blank=True, null=True, upload_to='communes/bannieres/', verbose_name='Bannière')),
                ('couleur_primaire', models.CharField(default='#0066CC', max_length=7, verbose_name='Couleur primaire')),
                ('couleur_secondaire', models.CharField(default='#004499', max_length=7, verbose_name='Couleur secondaire')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('historique', models.TextField(blank=True, verbose_name='Historique')),
                ('mot_du_maire', models.TextField(blank=True, verbose_name='Mot du maire')),
                ('nom_maire', models.CharField(blank=True, max_length=255, verbose_name='Nom du maire')),
                ('photo_maire', models.ImageField(blank=True, null=True, upload_to='communes/maires/', verbose_name='Photo du maire')),
                ('horaires_ouverture', models.JSONField(blank=True, default=dict, verbose_name='Horaires d ouverture')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('active', 'Active'), ('suspendue', 'Suspendue'), ('desactivee', 'Désactivée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date validation')),
                ('site', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commune', to='sites.site')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communes', to='communes.departement')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DemandeCreationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commune', models.CharField(max_length=255, verbose_name='Nom de la commune')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='Population approximative')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('nom_referent', models.CharField(max_length=255, verbose_name='Nom du référent')),
                ('fonction_referent', models.CharField(max_length=255, verbose_name='Fonction')),
                ('email_referent', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone_referent', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('motivation', models.TextField(blank=True, verbose_name='Motivation / Attentes')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='demandes/', verbose_name='Document justificatif')),
                ('accepte_charte', models.BooleanField(default=False, verbose_name='Accepte la charte')),
                ('accepte_confidentialite', models.BooleanField(default=False, verbose_name='Accepte politique confidentialité')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('notes_admin', models.TextField(blank=True, verbose_name='Notes administrateur')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('commune_creee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_creation', to='communes.commune')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communes.departement')),
            ],
            options={
                'verbose_name': 'Demande de création',
                'verbose_name_plural': 'Demandes de création',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='EquipeMunicipale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('fonction', models.CharField(choices=[('maire', 'Maire'), ('adjoint', 'Adjoint au Maire'), ('conseiller', 'Conseiller Municipal'), ('secretaire', 'Secrétaire Général')], max_length=50, verbose_name='Fonction')),
                ('fonction_detail', models.CharField(blank=True, max_length=255, verbose_name='Délégation / Détail')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='communes/equipe/', verbose_name='Photo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('biographie', models.TextField(blank=True, verbose_name='Biographie')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre affichage')),
                ('est_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='communes.commune')),
            ],
            options={
                'verbose_name': 'Membre équipe municipale',
                'verbose_name_plural': 'Équipe municipale',
                'ordering': ['ordre', 'fonction'],
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='communes.region'),
        ),
        migrations.CreateModel(
            name='ServiceMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du service')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('responsable', models.CharField(blank=True, max_length=255, verbose_name='Responsable')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('horaires', models.TextField(blank=True, verbose_name='Horaires')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='Icône (classe CSS)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='communes.commune')),
            ],
            options={
                'verbose_name': 'Service Municipal',
                'verbose_name_plural': 'Services Municipaux',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
