# Generated by Django 6.0 on 2025-12-04 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mairie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=255, verbose_name="Nom de la mairie"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="Slug URL"
                    ),
                ),
                ("localisation", models.TextField(verbose_name="Adresse complète")),
                (
                    "contact",
                    models.CharField(
                        max_length=255, verbose_name="Contact (téléphone/email)"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="mairies/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code postal"
                    ),
                ),
                (
                    "ville",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="Région"),
                ),
                (
                    "pays",
                    models.CharField(
                        default="Cameroun", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "site_web",
                    models.URLField(blank=True, verbose_name="Site web officiel"),
                ),
                (
                    "email_contact",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de contact"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "couleur_primaire",
                    models.CharField(
                        default="#0066CC", max_length=7, verbose_name="Couleur primaire"
                    ),
                ),
                (
                    "couleur_secondaire",
                    models.CharField(
                        default="#004499",
                        max_length=7,
                        verbose_name="Couleur secondaire",
                    ),
                ),
                (
                    "banniere",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="mairies/bannieres/",
                        verbose_name="Bannière",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Description de la mairie"
                    ),
                ),
                ("historique", models.TextField(blank=True, verbose_name="Historique")),
                (
                    "mot_du_maire",
                    models.TextField(blank=True, verbose_name="Mot du maire"),
                ),
                (
                    "nom_maire",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nom du maire"
                    ),
                ),
                (
                    "photo_maire",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="mairies/maires/",
                        verbose_name="Photo du maire",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de validation"),
                            ("active", "Active"),
                            ("suspendue", "Suspendue"),
                            ("desactivee", "Désactivée"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de validation"
                    ),
                ),
                (
                    "horaires_ouverture",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Horaires d'ouverture"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mairie",
                "verbose_name_plural": "Mairies",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="DemandeCreationSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_mairie",
                    models.CharField(max_length=255, verbose_name="Nom de la mairie"),
                ),
                ("localisation", models.TextField(verbose_name="Adresse complète")),
                ("contact", models.CharField(max_length=255, verbose_name="Contact")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="Téléphone"),
                ),
                (
                    "nom_demandeur",
                    models.CharField(max_length=255, verbose_name="Nom du demandeur"),
                ),
                (
                    "fonction_demandeur",
                    models.CharField(
                        max_length=255, verbose_name="Fonction du demandeur"
                    ),
                ),
                (
                    "justificatif",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="demandes/justificatifs/",
                        verbose_name="Document justificatif",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours de traitement"),
                            ("validee", "Validée"),
                            ("rejetee", "Rejetée"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "motif_rejet",
                    models.TextField(blank=True, verbose_name="Motif de rejet"),
                ),
                (
                    "date_demande",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de demande"
                    ),
                ),
                (
                    "date_traitement",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de traitement"
                    ),
                ),
                (
                    "mairie_creee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demande_creation",
                        to="mairies.mairie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de création de site",
                "verbose_name_plural": "Demandes de création de site",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.CreateModel(
            name="ServiceMunicipal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=255, verbose_name="Nom du service"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "responsable",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Responsable"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("horaires", models.TextField(blank=True, verbose_name="Horaires")),
                (
                    "icone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Icône (classe CSS)"
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "mairie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="mairies.mairie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Municipal",
                "verbose_name_plural": "Services Municipaux",
                "ordering": ["ordre", "nom"],
            },
        ),
    ]
